<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Login Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'index.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'painter@adobe.com',
		'to' => 'painter@adobe.com'
	),
	'fields' => array(
		'custom_U257' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'ชื่อผู้ใช้งาน',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'ชื่อผู้ใช้งาน\' is required.'
			)
		),
		'Email' => array(
			'order' => 1,
			'type' => 'email',
			'label' => 'รหัสผ่าน',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'รหัสผ่าน\' is required.',
				'format' => 'Field \'รหัสผ่าน\' has an invalid email.'
			)
		)
	)
);

process_form($form);
?>
